---
# See ../DEPENDENCIES.md#workaround-for-other-dependencies
name: Dependabot hack
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - never-trigger-this-dependabot-hack-workflow

jobs:

  dependabot_hack:
    name: Ensure dependabot version checks
    runs-on: ubuntu-22.04
    steps:

      # update the version in these places manually when Dependabot changes it here:
      # 1. the base image in the Dockerfile
      # 2. the base image in the devcontainer Dockerfile
      # 3. github_tag_and_release.yml
      # 4. integration_test.yml
      # 5. virtual_test.yml
      # 6. the go.mod (if it is a major or minor version change e.g. 1.14 to 1.15)
      - uses: golang/go@go1.21.6

      # update the versions in the devcontainer Dockerfile manually, too
      - uses: golang/tools@gopls/v0
      - uses: go-delve/delve@v1
      - uses: golangci/golangci-lint@v1
      - uses: SpectoLabs/hoverfly@v1.7.0
